# Generated by Django 5.2.13 on 2026-04-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaptureEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='posters/%Y/%m/%d/')),
                ('eventName', models.CharField(blank=True, max_length=200, verbose_name='행사명')),
                ('startDate', models.DateField(blank=True, null=True, verbose_name='시작일')),
                ('endDate', models.DateField(blank=True, null=True, verbose_name='종료일')),
                ('description', models.TextField(blank=True, verbose_name='상세 내용')),
                ('raw_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
