# Generated by Django 5.2.13 on 2026-04-22 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='captureevent',
            old_name='endDate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='captureevent',
            old_name='eventName',
            new_name='event_name',
        ),
        migrations.RenameField(
            model_name='captureevent',
            old_name='startDate',
            new_name='start_date',
        ),
    ]
